apiVersion: v1
kind: Namespace
metadata:
  name: bridgecrew
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bridgecrew
  namespace: bridgecrew
---
### View all resources EXCEPT secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridgecrew-view
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - podsecuritypolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterrolebindings
  - clusterroles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bridgecrew
subjects:
- kind: ServiceAccount
  name: bridgecrew
  namespace: bridgecrew
roleRef:
  kind: ClusterRole
  name: bridgecrew-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bridgecrew
  namespace: bridgecrew
  annotations:
    bridgecrew.io/skip1: CKV_K8S_22=Checkov requires filesystem write access to dump resource definitions
    bridgecrew.io/skip2: CKV_K8S_38=Service Account is required for read-only API access
    bridgecrew.io/skip3: CKV_K8S_14=Preferring latest rules every run - image pull always
    bridgecrew.io/skip4: CKV_K8S_43=Preferring latest rules every run - image pull always
spec:
  # Minutes, Hours, Day of Month (1-31), Month (1-12), Day of Week (0-6)
  schedule: "0 * * * *"
  jobTemplate:
    metadata:
      annotations:
        bridgecrew.io/skip1: CKV_K8S_22=Checkov requires filesystem write access to dump resource definitions
        bridgecrew.io/skip2: CKV_K8S_38=Service Account is required for read-only API access
        bridgecrew.io/skip3: CKV_K8S_14=Preferring latest rules every run - image pull always
        bridgecrew.io/skip4: CKV_K8S_43=Preferring latest rules every run - image pull always
    spec:
      template:
        metadata:
          annotations:
            seccomp.security.alpha.kubernetes.io/pod: runtime/default
            bridgecrew.io/skip1: CKV_K8S_22=Checkov requires filesystem write access to dump resource definitions
            bridgecrew.io/skip2: CKV_K8S_38=Service Account is required for read-only API access
            bridgecrew.io/skip3: CKV_K8S_14=Preferring latest rules every run - image pull always
            bridgecrew.io/skip4: CKV_K8S_43=Preferring latest rules every run - image pull always
        spec:
          securityContext:
            runAsUser: 12000
            runAsNonRoot: true
          restartPolicy: Never
          serviceAccountName: bridgecrew
          containers:
            - name: bridgecrew
              image: bridgecrew/bridgecrew-k8s:latest
              imagePullPolicy: Always
              #resources:
              #  requests:
              #    memory: "128Mi"
              #    cpu: "500m"
              #  limits:
              #    memory: "128Mi"
              #    cpu: "500m"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - name: bridgecrew-rt-secret
                  mountPath: "/etc/bridgecrew"
                  readOnly: true
          volumes:
            - name: bridgecrew-rt-secret
              secret:
                secretName: bridgecrew-rt-secret
                optional: true


